kind = "mobile"
previewPath = "/mobile/"
title = "Cuphead UI"
version = "1.0.0"
id = "artifacts/mobile-app"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
localPort = 24382
name = "expo"
paths = ["/mobile/"]

[services.development]
run = "pnpm --filter @workspace/mobile-app run dev"

[services.env]
PORT = "24382"
BASE_PATH = "/mobile/"

[services.production]
build = ["pnpm", "--filter", "@workspace/mobile-app", "run", "build"]
run = ["pnpm", "--filter", "@workspace/mobile-app", "run", "serve"]
